# Exit Codes
EXIT_SUCCESS = 0
EXIT_ERROR = 1
EXIT_INVALID_ARGS = 2
EXIT_MISSING_DEPENDENCY = 3
EXIT_PARTIAL_FAILURE = 4
EXIT_INTERRUPTED = 130

# FastSurfer Constraints
MIN_FASTSURFER_VERSION = (2, 4, 0)

# Defaults
DEFAULT_MAX_CASES = 1000
